CI: Add thresholds for models accuracy tests (#210)
* CI: Add threshold for models accuray tests

* Update .github/scripts/atom_test.sh

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

---------

Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>

diff --git a/.github/workflows/atom-test.yaml b/.github/workflows/atom-test.yaml
--- a/.github/workflows/atom-test.yaml
+++ b/.github/workflows/atom-test.yaml
@@ -11,6 +11,11 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
 
+env:
+  ATOM_BASE_NIGTHLY_IMAGE: rocm/atom-dev:latest
+  GITHUB_REPO_URL: ${{ github.event.pull_request.head.repo.clone_url || 'https://github.com/ROCm/ATOM.git' }}
+  GITHUB_COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
+
 jobs:
   pre-checks:
     uses: ./.github/workflows/pre-checks.yaml
@@ -18,8 +23,73 @@ jobs:
       black: true
       ruff: true
 
-  atom:
+  build_atom_image:
     needs: [pre-checks]
+    name: Build ATOM image
+    runs-on: build-only-atom
+    steps:
+      - name: Checkout ATOM repo
+        if: ${{ !github.event.pull_request.head.repo.fork }}
+        uses: actions/checkout@v4
+
+      - name: Generate Dockerfile
+        if: ${{ !github.event.pull_request.head.repo.fork }}
+        run: |
+          cat <<EOF > Dockerfile.mod
+          FROM ${{ env.ATOM_BASE_NIGTHLY_IMAGE }}
+          RUN pip install -U lm-eval[api]
+          RUN pip show lm-eval || true
+          RUN pip install hf_transfer
+          RUN pip show hf_transfer || true
+          RUN echo "=== Aiter version BEFORE uninstall ===" && pip show amd-aiter || true
+          RUN pip uninstall -y amd-aiter
+          RUN pip install --upgrade "pybind11>=3.0.1"
+          RUN pip show pybind11
+          RUN wget https://github.com/stedolan/jq/releases/download/jq-1.7/jq-linux64 -O jq
+          RUN chmod +x jq
+          RUN mv jq /usr/local/bin/jq
+          RUN rm -rf /app/aiter-test
+          RUN git clone --depth 1 https://github.com/ROCm/aiter.git /app/aiter-test && \\
+              cd /app/aiter-test && \\
+              git checkout HEAD && \\
+              git submodule sync && git submodule update --init --recursive && \\
+              MAX_JOBS=64 PREBUILD_KERNELS=0 GPU_ARCHS=gfx950 python3 setup.py develop
+          RUN echo "=== Aiter version AFTER installation ===" && pip show amd-aiter || true
+          
+          RUN echo "=== ATOM version BEFORE uninstall ===" && pip show atom || true
+          RUN pip uninstall -y atom
+          RUN rm -rf /app/ATOM
+          RUN git clone ${{ env.GITHUB_REPO_URL }} /app/ATOM && \\
+              cd /app/ATOM && \\
+              git checkout ${{ env.GITHUB_COMMIT_SHA }} && \\
+              pip install -e .
+
+          RUN echo "=== ATOM version AFTER installation ===" && pip show atom || true
+          EOF
+
+      - name: Build Docker image 
+        if: ${{ !github.event.pull_request.head.repo.fork }}
+        run: |
+          docker build --network=host \
+            --no-cache \
+            -t atom_test:ci \
+            -f Dockerfile.mod .
+          
+      - name: Push Docker image
+        if: ${{ !github.event.pull_request.head.repo.fork }}
+        run: |
+          IMAGE_TAG=rocm/atom-dev:pre-build-${{ env.GITHUB_COMMIT_SHA }}
+          docker tag atom_test:ci $IMAGE_TAG
+          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+          docker push $IMAGE_TAG
+
+      - name: Success message
+        if: ${{ !github.event.pull_request.head.repo.fork }}
+        run: |
+          echo "Successfully prepared image: $IMAGE_TAG"
+
+  atom:
+    needs: [pre-checks, build_atom_image]
     if: ${{ needs.pre-checks.result == 'success' && (!github.event.pull_request || github.event.pull_request.draft == false) }}
     name: ATOM Test
     strategy:
@@ -31,55 +101,60 @@ jobs:
             model_path: "meta-llama/Meta-Llama-3-8B-Instruct"
             extraArgs: "--kv_cache_dtype fp8"
             env_vars: ""
+            accuracy_test_threshold: "0.73"
             runner: linux-atom-mi355-1
           - model_name: "Llama-3.3-70B-Instruct-MXFP4-Preview"
             model_path: "amd/Llama-3.3-70B-Instruct-MXFP4-Preview"
             extraArgs: "--kv_cache_dtype fp8"
             env_vars: ""
+            accuracy_test_threshold: "0.88"
             runner: linux-atom-mi355-1
           - model_name: "DeepSeek-R1-0528"
             model_path: "deepseek-ai/DeepSeek-R1-0528"
             extraArgs: "--kv_cache_dtype fp8 -tp 8"
             env_vars: ""
+            accuracy_test_threshold: "0.94"
             runner: atom-mi355-8gpu.predownload
           - model_name: "DeepSeek-R1-0528 MTP"
             model_path: "deepseek-ai/DeepSeek-R1-0528"
             extraArgs: "--kv_cache_dtype fp8 -tp 8 --method mtp"
             env_vars: ""
+            accuracy_test_threshold: "0.94"
             runner: atom-mi355-8gpu.predownload
           - model_name: "DeepSeek-R1-0528-FP4"
             model_path: "amd/DeepSeek-R1-0528-mtp-mxfp4"
             extraArgs: "--kv_cache_dtype fp8 -tp 8"
             env_vars: ""
+            accuracy_test_threshold: "0.93"
             runner: atom-mi355-8gpu.predownload
           - model_name: "DeepSeek-R1-0528-FP4 MTP"
             model_path: "amd/DeepSeek-R1-0528-mtp-mxfp4"
             extraArgs: "--kv_cache_dtype fp8 -tp 8 --method mtp"
             env_vars: ""
+            accuracy_test_threshold: "0.93"
             runner: atom-mi355-8gpu.predownload
           - model_name: "gpt-oss-120b"
             model_path: "openai/gpt-oss-120b"
             extraArgs: "--kv_cache_dtype fp8"
             env_vars: |
               ATOM_GPT_OSS_MODEL=1
+            accuracy_test_threshold: "0.38"
             runner: linux-atom-mi355-1
           - model_name: "gpt-oss-120b (2 GPUs)"
             model_path: "openai/gpt-oss-120b"
             extraArgs: "--kv_cache_dtype fp8 -tp 2 --enable-dp-attention --enable-expert-parallel"
             env_vars: |
               ATOM_GPT_OSS_MODEL=1
+            accuracy_test_threshold: "0.38"
             runner: linux-atom-mi355-4
           - model_name: "Qwen3-235B-A22B-Instruct-2507-FP8"
             model_path: "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8"
             extraArgs: "--kv_cache_dtype fp8 -tp 8 --enable-expert-parallel"
             env_vars: |
               ATOM_ENABLE_QK_NORM_ROPE_CACHE_QUANT_FUSION=1
+            accuracy_test_threshold: "0.87"
             runner: atom-mi355-8gpu.predownload
     runs-on: ${{ matrix.runner }}
-    env:
-      ATOM_BASE_NIGTHLY_IMAGE: rocm/atom-dev:latest
-      GITHUB_REPO_URL: ${{ github.event.pull_request.head.repo.clone_url || 'https://github.com/ROCm/ATOM.git' }}
-      GITHUB_COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.event.head_commit.id }}
 
     steps:
       - name: Kill all Docker containers
@@ -106,11 +181,8 @@ jobs:
       - name: Checkout ATOM repo
         uses: actions/checkout@v4
 
-      - name: Pull ATOM base image
-        run: |
-          docker pull ${{ env.ATOM_BASE_NIGTHLY_IMAGE }}
-
-      - name: Generate Dockerfile
+      - name: Generate Dockerfile for forked repo
+        if: ${{ github.event.pull_request.head.repo.fork }}
         run: |
           cat <<EOF > Dockerfile.mod
           FROM ${{ env.ATOM_BASE_NIGTHLY_IMAGE }}
@@ -141,7 +213,8 @@ jobs:
           RUN echo "=== ATOM version AFTER installation ===" && pip show atom || true
           EOF
 
-      - name: Build Docker image
+      - name: Build Docker image for forked repo
+        if: ${{ github.event.pull_request.head.repo.fork }}
         run: |
           docker build --network=host \
             --no-cache \
@@ -175,6 +248,13 @@ jobs:
           echo "Model-specific environment variables for ${{ matrix.model_name }}:"
           cat /tmp/env_file.txt
 
+          if [ "${{ github.event.pull_request.head.repo.fork }}" = "true" ]; then
+            IMAGE_TAG=atom_test:ci
+          else
+            IMAGE_TAG=rocm/atom-dev:pre-build-${{ env.GITHUB_COMMIT_SHA }}
+          fi
+
+
           docker run -dt --device=/dev/kfd $DEVICE_FLAG \
           -v "${GITHUB_WORKSPACE:-$PWD}":/workspace \
           $MODEL_MOUNT \
@@ -192,7 +272,7 @@ jobs:
           -v "${{ github.workspace }}:/workspace" \
           -w /workspace \
           --name atom_test \
-          atom_test:ci
+          $IMAGE_TAG
 
         env:
           GITHUB_WORKSPACE: ${{ github.workspace }}
@@ -284,6 +364,30 @@ jobs:
             .github/scripts/atom_test.sh accuracy $model_path
           " 2>&1 | tee atom_accuracy_output.txt
       
+      - name: Check accuracy test results
+        if: success()
+        run: |
+          result_file=$(ls -1t accuracy_test_results/*.json 2>/dev/null | head -n 1)
+          if [ -z "$result_file" ] || [ ! -f "$result_file" ]; then
+              echo "ERROR: No results JSON file found in accuracy_test_results/"
+              exit 2
+          else
+              echo "RESULT_FILE: $result_file"
+          fi
+          flexible_extract_value=$(jq '.results.gsm8k["exact_match,flexible-extract"]' "$result_file")
+          echo "Flexible extract value: $flexible_extract_value"
+          echo "Accuracy test threshold: ${{ matrix.accuracy_test_threshold }}"
+
+          # Compare as float: use awk for decimal value comparison
+          result=$(awk -v val="$flexible_extract_value" -v threshold="${{ matrix.accuracy_test_threshold }}" 'BEGIN {print (val < threshold) ? 1 : 0}')
+          if [ "$result" -eq 1 ]; then
+            echo "Accuracy test failed: Flexible extract value $flexible_extract_value is less than the threshold ${{ matrix.accuracy_test_threshold }}."
+            exit 1
+          else
+            echo "Accuracy test passed: Flexible extract value $flexible_extract_value is greater than or equal to the threshold ${{ matrix.accuracy_test_threshold }}."
+            exit 0
+          fi
+
       - name: Collect Test Summary
         if: success()
         run: |
@@ -305,7 +409,7 @@ jobs:
           set -x
           echo "========== Cleaning up workspace =========="
           if [[ ${{ matrix.runner }} == atom-mi355-8gpu.predownload ]]; then
-            docker run --rm -v "${GITHUB_WORKSPACE:-$PWD}":/workspace -w /workspace --privileged rocm/pytorch:latest bash -lc "rm -rf /workspace/atom/ /workspace/aiter/" || true
+            docker run --rm -v "${GITHUB_WORKSPACE:-$PWD}":/workspace -w /workspace --privileged rocm/pytorch:latest bash -lc "ls -la /workspace/ && rm -rf /workspace/*" || true
           fi
           docker stop atom_test || true
           docker rm atom_test || true
